# Use a lightweight PyTorch image with CUDA support
FROM pytorch/pytorch:2.4.0-cuda12.1-cudnn9-runtime

# Set working directory
WORKDIR /app
ENV HF_HOME=/app/hf_cache

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    git-lfs \
    && rm -rf /var/lib/apt/lists/*


# Install shared requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY . .

ENTRYPOINT ["python", "train.py"]
