# 1. Base image: NVIDIA cuda
FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

# 2. Set working directory inside container
WORKDIR /app

# System deps
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cu121

# 3. Copy dependency list first (for caching)
COPY requirements.txt .

# 4. Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copy the rest of the experiment code
COPY . .

# 6. Default command to run the experiment
ENTRYPOINT ["python3", "train.py"]

