# Base image: slim Python
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install CPU dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu

#RUN pip install --no-cache-dir torch torchvision
#RUN pip install --no-cache-dir torch==2.2.2+cpu torchvision==0.17.2+cpu --extra-index-url https://download.pytorch.org/whl/cpu

# Install shared dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the experiment code
COPY . .

ENTRYPOINT ["python", "train.py"]

